# -*- coding: utf-8 -*-
"""A090H317.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Y_KBXTneSlyBywswewFC4gQOa3x47i4

# HASH 雜湊函數
1005
- md5
- sha1



- linux指令
- md5sum
- Colab使用方式 : !md5sum 檔案名稱
"""

!md5sum --help

!echo Iamstubie > 1005.txt

!cat 1005.txt

!md5sum 1005.txt

!echo iamstubie > 1005a.txt

!cat 1005a.txt

!md5sum 1005a.txt